image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # Запускаем SUT,
  # имя файла SUT будет отличаться в каждой задаче.
  # & означает, что в фоновом режиме не блокируем терминал для запуска тестов, 
  # обязательно должен быть для запуска SUT в CI
  - java -jar ./artifacts/app-mbank.jar &
  - chmod +x gradlew

build_script:
  # Запускаем автотесты
  # Для проектов на базе Selenide необходимо$ git push origin main
To github.com:neshutnick/avt2rest.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'github.com:neshutnick/avt2rest.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
 добавить параметр для запуска браузера
  # в headless режиме -Dselenide.headless=true, параметр --info должен остаться
  - ./gradlew test --info